- name: deployment
  hosts: all
  become: True
  vars:
    nexus_url: http://43.206.113.174:8081/repository
    repository_type: 	java-maven-war-app-release
    group_id: com/efsavage
    artifact_id: hello-world-war
    version: 1.0.0
    build_number: "{{build_number}}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{repository_type}}/{{group_id}}/{{artifact_id}}/{{version}}-{{build_number}}/{{artifact_id}}-{{version}}-{{ build_number}}.war"
      dest: /tmp
      username: admin
      password: 0280719930

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war /home/ec2-user/faangler.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/first.war /home/ec2-user/apache-tomcat-9.0.72/webapps/first.war

  - name: remove the artifact
    ansible.builtin.shell: "rm -rf cp /home/ec2-user/first.war"
    
  - name: restart systemd, enable tomcat service and start tomcat service
    ansible.builtin.systemd:
       name: tomcat.service
       daemon-reload: yes
       state: started
       enabled: yes